version: '3.8'
services:
  app:
    container_name: nhrigs
    image: ghcr.io/iamtakagi/nhrigs:latest
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
      - PORT=8080
    ports:
      - 8080:8080